#!/bin/bash

# Demo: Enhanced Installation Feature

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  Local Testing for Azure Managed Redis Terraform Repository   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "==> Checking prerequisites..."
echo "✗ Missing required tools: tflint"
echo ""
echo "These tools are needed to run local validation checks."
echo ""
echo "Do you want to install missing tools now? (y/n)"
echo ""
echo "If you answer 'y', the script will run:"
echo "  brew install tflint"
echo ""
echo "If you answer 'n', it will show manual installation instructions for all platforms."
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "📋 Usage Examples:"
echo ""
echo "1. Install missing tools:"
echo "   ./scripts/test-actions-locally.sh install"
echo ""
echo "2. Run tests (will check prerequisites first):"
echo "   ./scripts/test-actions-locally.sh"
echo ""
echo "3. Run specific tests:"
echo "   ./scripts/test-actions-locally.sh lint"
echo ""
