name: Test Simple Example

on:
  workflow_dispatch:
    inputs:
      cleanup:
        description: 'Clean up resources after testing'
        required: false
        default: true
        type: boolean

permissions:
  id-token: write    # Required for OIDC authentication
  contents: read

env:
  TF_VERSION: "1.7.5"
  ARM_SKIP_PROVIDER_REGISTRATION: "true"

jobs:
  test-simple:
    name: Test Simple Example
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: false

    - name: Set ARM Environment Variables
      run: |
        echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        echo "ARM_USE_OIDC=true" >> $GITHUB_ENV

    - name: Deploy Simple Example
      id: deploy
      run: |
        cd examples/simple
        
        # Generate unique resource names
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        REDIS_NAME="redis-simple-test-${TIMESTAMP}"
        
        # Create terraform.tfvars
        cat > terraform.tfvars << EOF
        resource_group_name = "rg-azure-managed-redis-terraform"
        location = "eastus"
        redis_name = "${REDIS_NAME}"
        environment = "testing"
        create_resource_group = false
        EOF
        
        echo "terraform_dir=$(pwd)" >> $GITHUB_OUTPUT
        echo "redis_name=${REDIS_NAME}" >> $GITHUB_OUTPUT
        
        # Initialize and deploy
        terraform init
        terraform plan -input=false
        terraform apply -auto-approve -input=false
        
        echo "✅ Simple example deployed successfully"

    - name: Test Redis Connectivity
      run: |
        cd examples/simple
        
        # Get connection string
        CONNECTION_STRING=$(terraform output -raw connection_string)
        
        # Install redis-cli for testing
        sudo apt-get update && sudo apt-get install -y redis-tools
        
        echo "⏳ Waiting for Azure Redis keys to propagate (this can take 20-40 seconds)..."
        sleep 30
        
        # Retry function for Redis commands
        retry_redis_command() {
          local max_retries=3
          local retry_delay=10
          local attempt=1
          local cmd="$@"
          
          while [ $attempt -le $max_retries ]; do
            output=$(eval "$cmd" 2>&1)
            exit_code=$?
            
            if echo "$output" | grep -q "WRONGPASS\|NOAUTH"; then
              echo "⚠️  Attempt $attempt/$max_retries: Authentication still propagating, waiting ${retry_delay}s..."
              sleep $retry_delay
              attempt=$((attempt + 1))
            elif [ $exit_code -eq 0 ]; then
              echo "$output"
              return 0
            else
              echo "❌ Command failed: $output"
              return 1
            fi
          done
          
          echo "❌ Command failed after $max_retries attempts"
          return 1
        }
        
        # Test basic Redis operations
        echo "Testing Redis connectivity with PING..."
        if ! retry_redis_command "redis-cli -u \"$CONNECTION_STRING\" ping"; then
          echo "❌ PING test failed"
          exit 1
        fi
        echo "✅ PING successful"
        
        echo "Testing basic SET/GET operations..."
        if ! retry_redis_command "redis-cli -u \"$CONNECTION_STRING\" SET test \"simple-example-test-\$(date +%s)\""; then
          echo "❌ SET command failed"
          exit 1
        fi
        echo "✅ SET successful"
        
        RESULT=$(retry_redis_command "redis-cli -u \"$CONNECTION_STRING\" GET test")
        
        if [ -n "$RESULT" ]; then
          echo "✅ Redis connectivity test successful"
          echo "  - GET result: $RESULT"
        else
          echo "❌ Redis connectivity test failed"
          exit 1
        fi

    - name: Display Connection Information
      run: |
        cd examples/simple
        
        echo "## Simple Example Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Deployment Information" >> $GITHUB_STEP_SUMMARY
        echo "- Redis Name: ${{ steps.deploy.outputs.redis_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- Resource Group: rg-azure-managed-redis-terraform" >> $GITHUB_STEP_SUMMARY
        echo "- Location: East US" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Test Status" >> $GITHUB_STEP_SUMMARY
        echo "✅ Deployment: Successful" >> $GITHUB_STEP_SUMMARY
        echo "✅ Connectivity: Working" >> $GITHUB_STEP_SUMMARY
        echo "✅ Basic Operations: Functional" >> $GITHUB_STEP_SUMMARY

    - name: Clean Up Resources
      if: always() && github.event.inputs.cleanup == 'true'
      run: |
        cd examples/simple
        
        echo "Cleaning up test resources..."
        terraform destroy -auto-approve -input=false
        echo "✅ Resources cleaned up"
