name: Test Geo-Replication Example

on:
  workflow_dispatch:
    inputs:
      cleanup:
        description: 'Clean up resources after testing'
        required: false
        default: true
        type: boolean

permissions:
  id-token: write    # Required for OIDC authentication
  contents: read

env:
  TF_VERSION: "1.7.5"
  ARM_SKIP_PROVIDER_REGISTRATION: "true"

jobs:
  test-geo-replication:
    name: Test Geo-Replication Example
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: false

    - name: Set ARM Environment Variables
      run: |
        echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        echo "ARM_USE_OIDC=true" >> $GITHUB_ENV

    - name: Deploy Geo-Replication Example
      id: deploy
      run: |
        cd examples/geo-replication
        
        # Generate unique resource names
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        PROJECT_NAME="redis-geo-test-${TIMESTAMP}"
        
        # Create terraform.tfvars
        cat > terraform.tfvars << EOF
        project_name = "${PROJECT_NAME}"
        primary_location = "eastus"
        secondary_location = "westus2"
        environment = "testing"
        redis_sku = "Balanced_B1"
        EOF
        
        echo "terraform_dir=$(pwd)" >> $GITHUB_OUTPUT
        echo "project_name=${PROJECT_NAME}" >> $GITHUB_OUTPUT
        
        # Initialize and deploy
        terraform init
        terraform plan -input=false
        terraform apply -auto-approve -input=false
        
        echo "✅ Geo-replication example deployed successfully"

    - name: Test Primary Region Redis
      run: |
        cd examples/geo-replication
        
        # Get primary connection details
        PRIMARY_HOSTNAME=$(terraform output -raw primary_hostname)
        PRIMARY_KEY=$(terraform state show 'module.primary_redis.data.azapi_resource_action.database_keys[0]' | grep 'primaryKey' | sed -n 's/.*primaryKey[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p')
        PORT=10000
        
        # Install redis-cli for testing
        sudo apt-get update && sudo apt-get install -y redis-tools
        
        # Test primary region
        echo "Testing primary region Redis connectivity..."
        redis-cli -h "$PRIMARY_HOSTNAME" -p "$PORT" --tls -a "$PRIMARY_KEY" --no-auth-warning ping
        
        # Set test data in primary
        redis-cli -h "$PRIMARY_HOSTNAME" -p "$PORT" --tls -a "$PRIMARY_KEY" --no-auth-warning JSON.SET primary:test $ '{
          "region": "primary",
          "location": "eastus",
          "test_data": "geo-replication-primary-test",
          "timestamp": "'$(date -Iseconds)'"
        }'
        
        # Verify primary data
        PRIMARY_RESULT=$(redis-cli -h "$PRIMARY_HOSTNAME" -p "$PORT" --tls -a "$PRIMARY_KEY" --no-auth-warning JSON.GET primary:test $.region)
        
        if [[ "$PRIMARY_RESULT" == *"primary"* ]]; then
          echo "✅ Primary region Redis test successful"
        else
          echo "❌ Primary region Redis test failed"
          exit 1
        fi

    - name: Test Secondary Region Redis
      run: |
        cd examples/geo-replication
        
        # Get secondary connection details
        SECONDARY_HOSTNAME=$(terraform output -raw secondary_hostname)
        SECONDARY_KEY=$(terraform state show 'module.secondary_redis.data.azapi_resource_action.database_keys[0]' | grep 'primaryKey' | sed -n 's/.*primaryKey[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p')
        PORT=10000
        
        # Test secondary region
        echo "Testing secondary region Redis connectivity..."
        redis-cli -h "$SECONDARY_HOSTNAME" -p "$PORT" --tls -a "$SECONDARY_KEY" --no-auth-warning ping
        
        # Set test data in secondary
        redis-cli -h "$SECONDARY_HOSTNAME" -p "$PORT" --tls -a "$SECONDARY_KEY" --no-auth-warning JSON.SET secondary:test $ '{
          "region": "secondary",
          "location": "westus2",
          "test_data": "geo-replication-secondary-test",
          "timestamp": "'$(date -Iseconds)'"
        }'
        
        # Verify secondary data
        SECONDARY_RESULT=$(redis-cli -h "$SECONDARY_HOSTNAME" -p "$PORT" --tls -a "$SECONDARY_KEY" --no-auth-warning JSON.GET secondary:test $.region)
        
        if [[ "$SECONDARY_RESULT" == *"secondary"* ]]; then
          echo "✅ Secondary region Redis test successful"
        else
          echo "❌ Secondary region Redis test failed"
          exit 1
        fi

    - name: Test Geo-Replication Search Capabilities
      run: |
        cd examples/geo-replication
        
        # Get connection details for both regions
        PRIMARY_HOSTNAME=$(terraform output -raw primary_hostname)
        PRIMARY_KEY=$(terraform state show 'module.primary_redis.data.azapi_resource_action.database_keys[0]' | grep 'primaryKey' | sed -n 's/.*primaryKey[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p')
        SECONDARY_HOSTNAME=$(terraform output -raw secondary_hostname)
        SECONDARY_KEY=$(terraform state show 'module.secondary_redis.data.azapi_resource_action.database_keys[0]' | grep 'primaryKey' | sed -n 's/.*primaryKey[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p')
        PORT=10000
        
        # Test RediSearch in primary region
        echo "Testing RediSearch in primary region..."
        redis-cli -h "$PRIMARY_HOSTNAME" -p "$PORT" --tls -a "$PRIMARY_KEY" --no-auth-warning FT.CREATE idx:products ON JSON PREFIX 1 product: SCHEMA $.name AS name TEXT $.category AS category TAG
        redis-cli -h "$PRIMARY_HOSTNAME" -p "$PORT" --tls -a "$PRIMARY_KEY" --no-auth-warning JSON.SET product:1 $ '{"name":"Laptop","category":"Electronics","region":"primary"}'
        PRIMARY_SEARCH=$(redis-cli -h "$PRIMARY_HOSTNAME" -p "$PORT" --tls -a "$PRIMARY_KEY" --no-auth-warning FT.SEARCH idx:products "Laptop")
        
        # Test RediSearch in secondary region
        echo "Testing RediSearch in secondary region..."
        redis-cli -h "$SECONDARY_HOSTNAME" -p "$PORT" --tls -a "$SECONDARY_KEY" --no-auth-warning FT.CREATE idx:users ON JSON PREFIX 1 user: SCHEMA $.name AS name TEXT $.city AS city TAG
        redis-cli -h "$SECONDARY_HOSTNAME" -p "$PORT" --tls -a "$SECONDARY_KEY" --no-auth-warning JSON.SET user:1 $ '{"name":"Alice","city":"Seattle","region":"secondary"}'
        SECONDARY_SEARCH=$(redis-cli -h "$SECONDARY_HOSTNAME" -p "$PORT" --tls -a "$SECONDARY_KEY" --no-auth-warning FT.SEARCH idx:users "Alice")
        
        if [[ "$PRIMARY_SEARCH" == *"Laptop"* ]] && [[ "$SECONDARY_SEARCH" == *"Alice"* ]]; then
          echo "✅ Geo-replication search capabilities test successful"
        else
          echo "❌ Geo-replication search capabilities test failed"
          exit 1
        fi

    - name: Display Connection Information
      run: |
        cd examples/geo-replication
        
        echo "## Geo-Replication Example Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Deployment Information" >> $GITHUB_STEP_SUMMARY
        echo "- Project Name: ${{ steps.deploy.outputs.project_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- Primary Region: East US" >> $GITHUB_STEP_SUMMARY
        echo "- Secondary Region: West US 2" >> $GITHUB_STEP_SUMMARY
        echo "- SKU: Balanced_B1" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Test Status" >> $GITHUB_STEP_SUMMARY
        echo "✅ Primary Deployment: Successful" >> $GITHUB_STEP_SUMMARY
        echo "✅ Secondary Deployment: Successful" >> $GITHUB_STEP_SUMMARY
        echo "✅ Primary Connectivity: Working" >> $GITHUB_STEP_SUMMARY
        echo "✅ Secondary Connectivity: Working" >> $GITHUB_STEP_SUMMARY
        echo "✅ RedisJSON (Both Regions): Functional" >> $GITHUB_STEP_SUMMARY
        echo "✅ RediSearch (Both Regions): Functional" >> $GITHUB_STEP_SUMMARY

    - name: Clean Up Resources
      if: always() && github.event.inputs.cleanup == 'true'
      run: |
        cd examples/geo-replication
        
        echo "Cleaning up test resources..."
        terraform destroy -auto-approve -input=false
        echo "✅ Resources cleaned up"
